### ISSUE TITLE
Messages overlapping in chat

### ISSUE THREAD

**Issue by alysamurray** [UPchieve/web#102]
If user 1 sends a long enough message then sends a second message, the second message will overlap the first message. 
<img width="467" alt="screen shot 2018-08-27 at 1 18 09 pm" src="https://user-images.githubusercontent.com/20755642/44674582-f8272300-a9fb-11e8-8414-eb876f0c70bb.png">

**Comment by lualparedes** [comment]
@alysamurray I'm going to close this because you added the same bug twice, lol (I chose to close this one instead of [the other](https://github.com/UPchieve/web/issues/103) because the other has more information).
