### ISSUE TITLE
Messages overlap in chat

### ISSUE THREAD

**Issue by alymurray** [UPchieve/web#103]
The invisible boxes that contain the text sent in chat messages should be able to expand past the halfway point of the chat box, and the other person's messages should not be right-aligned. the space that their text occupies should be right aligned, but the text inside that invisible box should be left aligned. Look at how iMessage works for reference.

<img width="467" alt="screen shot 2018-08-27 at 1 18 09 pm" src="https://user-images.githubusercontent.com/20755642/44674670-44726300-a9fc-11e8-9877-0dc2d13cdde2.png">

iMessage
<img width="467" alt="imessage example" src="https://user-images.githubusercontent.com/20755642/44674760-83081d80-a9fc-11e8-992e-b1e04fe9032f.png">

**Comment by lualparedes** [comment]
Solved with #114 #115 :hugs:
