### ISSUE TITLE
Taking the test for "College Counseling > Essay" crashes the backend server

### ISSUE THREAD

**Issue by lualparedes** [UPchieve/web#107]
## Steps to reproduce

1. Go to /training
2. Click on "College Counseling > Essay > Take quiz"
3. Click on "Start test" and  you'll notice that the progress bar doesn't work and the backend server crashes and logs this to the console:
```bash
# ...
/TrainingCtrl.js:67
        subcategories.map(function(subcategory) {
                     ^

TypeError: Cannot read property 'map' of undefined
# ...
```

## Notes

- Probably not a frontend issue

**Comment by ilakumar** [comment]
Fixed with this https://github.com/UPchieve/web/pull/116
