### ISSUE TITLE
Volunteer ESL quiz submission not working

### ISSUE THREAD

**Issue by alymurray** [UPchieve/web#121]
Volunteer says they answered all q's but it's not letting them submit, showing the error "you must answer all questions before submitting the quiz":

![upchieve 1](https://user-images.githubusercontent.com/20755642/46841493-43bc4300-cd96-11e8-8ddd-0e1bb85c066d.PNG)

**Comment by alymurray** [comment]
Just tested it with calculus and got the same error

**Comment by lualparedes** [comment]
Solved in #122
