### ISSUE TITLE
Add server-side pagination to the volunteer admin search route

### ISSUE THREAD

**Issue by ti2ger92** [UPchieve/web#241]
Right now, we have client-side pagination that loads all the volunteers at once and then visually cycles between pages of them. If we had 1,000 volunteers, that'd be a lot of data for the client to hold.

Implement server-side pagination that only sends the client the 20 (`PAGE_COUNT`) volunteer models at a time.

Something like: [https://codeforgeek.com/server-side-pagination-using-node-and-mongo/](https://codeforgeek.com/server-side-pagination-using-node-and-mongo/)

If you want, a bonus while you're at it: implement server-side filtering & sorting

**Comment by treykris** [comment]
First pr to resolve this issue: https://github.com/UPchieve/server/pull/334
