### ISSUE TITLE
Add status messages in chat sessions

### ISSUE THREAD

**Issue by ti2ger92** [UPchieve/web#242]
**Always send**

**Message 1:**

Hi there! Thanks for requesting help on UPchieve. 🙂

**Message 2:**

We're looking for a coach to pair you with now. This process typically takes 5-10 minutes.

**Message 3:**

While you're waiting, why don't you tell us what you need help with in the chat? You can write out any problems you're working on on the whiteboard too.
---
In the future, to give students better updates about what's going on, we'd need to allow volunteers to respond "Y" or "N" to our text message notification letting us know if they're available. Messages might look like:

**After 10 minutes (if still waiting for responses from volunteers):**

We're so sorry about the wait! We are still looking for coaches.

**After 20 mins or exhausting all volunteer options:**

We're so sorry! We aren't able to find a coach for your request right now. You can stay here and wait or try requesting help again in the future.
**This one would change once we have a submit a written question feature or a scheduling feature or some way to tell if there were more volunteers who were going to be available in the next hour....

**After finding a volunteer (volunteer responds "Y"):**

We found an available coach! They're logging in to help you now. Hang tight!
---

**After a volunteer joins the session**

**Message 4:**

Awesome! [Student Name], meet [Volunteer Name]! We hope you guys have a great time.
** In the future maybe we should even share some fun fact about the volunteer with the student. e.g. their favorite academic subject? current or prior college?

**Message 5:**

A couple reminders for you both:
- Practice online safety! Don't share personal information like your phone number or email.
- Click "end session" when you're done, and make sure to fill out the short feedback form that follows!

**Comment by jkeat** [comment]
Something like this has been added; closing
