### ISSUE TITLE
Occasional whiteboard lag

### ISSUE THREAD

**Issue by jkeat** [UPchieve/web#284]
- Browser sometimes severely slows down while using whiteboard
- Currently, we don't have specifics on reproducing
- One thing to note: reports of this happening are from volunteers with a large number of past sessions. This might be contributing to large socket.io data transmissions, which could, in turn, cause browser slow-down

**Comment by dmnisson** [comment]
I tried to reproduce this by populating my local database with over 100,000 sessions and adding them as past sessions to one of my test volunteers. I couldn't reproduce any issues with the whiteboard specifically, but I did notice that this triggered a massive slowdown when navigating between routes; this appears to result from the `/api/user` endpoint querying all of those past sessions from the database and calculating the volunteer session hours every time it is called. The PRs above address the issue that I found, which may be related to what some people are experiencing with the whiteboard.
