### ISSUE TITLE
Timezone conversion is incorrect, resulting in wrong availability data being sent to server

### ISSUE THREAD

**Issue by dmnisson** [UPchieve/web#292]
When the calendar is saved with the `America/Los_Angeles` timezone, the availability hours are shifted to the previous day before being sent to the server, instead of being shifted three hours ahead as they should be. The issue does not occur with the `America/New_York` timezone.

The issue may be related to the use of the current time to determine the user’s timezone offset; it seems to occur only at certain times of the day.

**Comment by jkeat** [comment]
Fixed by https://github.com/UPchieve/web/pull/293
