### ISSUE TITLE
Clicking outside of modals should close them

### ISSUE THREAD

**Issue by jkeat** [UPchieve/web#386]
Currently, the only way to close a modal on desktop is to click "cancel". You should also be able to close by clicking outside of the modal.

**Comment by ti2ger92** [comment]
Perhaps we could add an example from a vanilla install? I couldn't find one after a few minutes. For instance, when I visit `http://localhost:3000/edu/questions/new`, and click "See MathJax Guide", a modal pops up which does close when I click outside the modal.
