### ISSUE TITLE
Schedule view doesn't load properly

### ISSUE THREAD

**Issue by lualparedes** [UPchieve/web#69]
The first time a volunteer tries going to the schedule page it doesn’t load properly, in particular it seems like the columns and cells don’t show up. Then if you switch pages and come back it seems to load properly.

### Findings

I was running into this problem multiple times. Sometimes when I visited the page the schedule would show up, other times it wouldn't. This appears to be a network problem. The calendar won't fill in until the user's information has been retrieved, so this is most likely an issue with the app's ability to communicate with the database. I can't tell from my quick surmise where this problem is occurring, but I think that if we log the errors from each step in this process it should point us in the right direction.

**Comment by rossedwardsus** [comment]
I will try running this locally over the next few days and see if i come across it as well.

**Comment by jmromer** [comment]
Related:
https://app.asana.com/0/775116702697292/1115439483057742

**Comment by jkeat** [comment]
PR: https://github.com/UPchieve/web/pull/164
