### ISSUE TITLE
Volunteer can't see messages sent before entering session

### ISSUE THREAD

**Issue by lualparedes** [UPchieve/web#71]
Volunteer needs to be able to see all messages sent in chat and all things drawn on the whiteboard when they enter a session with a student (currently both whiteboard and chat will be empty/blank even if student was using them beforehand).

**Comment by rossedwardsus** [comment]
What does the volunteer see currently?  Is it just blank screen?  There will need to be a query done to load the current session data if it is not there already.

**Comment by rossedwardsus** [comment]
More just starting a discussion about this as it's a larger conversation that needs to be had about the overall usability of the app.  It can be discussed at a later time.

**Comment by jmromer** [comment]
PRs open for this here:
https://github.com/UPchieve/web/pull/152
https://github.com/UPchieve/server/pull/65

**Comment by jmromer** [comment]
Fixed by https://github.com/UPchieve/web/pull/155
